### ISSUE TITLE
Steam OS wont boot (post first boot)

### ISSUE THREAD

**Issue by w3bKodr** [ryanrudolfoba/SteamOS-microSD#2]
During first boot, after I input the wireless information and the time, the steam deck installed for a few minutes and then downloaded some updates. After that, it rebooted me into windows (from my SSD), I then shut down and booted off my microSD, and it just hangs at the steam deck logo.

**Comment by ryanrudolfoba** [comment]
I reformatted my SteamOS microSD yesterday and re-ran the script. Please see details below for a breakdown of time estimates -

1. After running the install script, power off the Steam Deck. Press VOLDOWN + UP then select the SteamOS microSD.

2. On initial reboot it takes about 2mins on the Steam logo, then goes to black screen for about 1min then it goes to the initial setup - language, timezone, wifi. 

3. It downloads and installs the initial update for about 5mins, then it gets stuck on 1sec. I just let it sit there and after ~2mins it completes and reboots. 

4. Power off the Steam Deck again then press VOLDOWN + POWER then select the SteamOS microSD. It goes to Steam logo and i wait for about 2mins but gets "stuck" for more than that so i randomly press the buttons - B A B A X Y and it goes to a black screen and continues to load.

5. Setup the language, timezone and wifi settings. Signin to Steam and then it will go to the game mode.

So on your issue it looks like you are stuck Steam logo on step4. Follow the B A B A X Y and let me know how it goes.

**Comment by w3bKodr** [comment]
Pressing random during boot while the steam logo was on screen caused it to boot up, thank you!
