### ISSUE TITLE
Recovery OS always auto mount /dev/mmcblk0p8 and cause script error

### ISSUE THREAD

**Issue by chrisxvin** [ryanrudolfoba/SteamOS-microSD#4]
Auto mount cause "Creating home partition..." error, mkfs.ext4 refused to execute when it is mounted.

So I try to manually create partition.
Then modify ~/tools/repair_device_sdcard.sh", turn "writePartitionTable" to "0" at line 340, re-run your script. Success.

May be you can add more check about partition mounted?
Thank you.

**Comment by ryanrudolfoba** [comment]
thanks for feedback. i'll see what i can do.

**Comment by chrisxvin** [comment]
Well...Sorry for not reading "Trouble Shooting".
I installed OS into SD card once, but stuck at first boot.
So I tried to re-install, then trigger the problem you say, the same partition layout. I just deleted all old parts, but did not create and format a new one.
Nevermind, my deck is working fine now.
Thank you for your great work!
